spring.datasource.url=jdbc:postgresql://localhost:5432/orderbook
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=orderbook_user
spring.datasource.password=orderbook_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.sql.init.mode=always
server.port=8082
