CREATE TABLE IF NOT EXISTS traders (
    id VARCHAR(32) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trader_id VARCHAR(32) NOT NULL,
    stock VARCHAR(32) NOT NULL CHECK (stock = UPPER(stock)),
    sector VARCHAR(64) NOT NULL CHECK (sector IN ('TECH', 'FINANCE', 'ENERGY', 'HEALTHCARE')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    side VARCHAR(16) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'FILLED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_orders_trader FOREIGN KEY (trader_id) REFERENCES traders(id),
    CONSTRAINT ck_orders_stock_sector CHECK (
        (sector = 'TECH' AND stock IN ('AAPL', 'MSFT', 'GOOGL', 'TSLA', 'NVDA'))
        OR (sector = 'FINANCE' AND stock IN ('JPM', 'GS', 'BAC', 'MS', 'WFC'))
        OR (sector = 'ENERGY' AND stock IN ('XOM'))
        OR (sector = 'HEALTHCARE' AND stock IN ('JNJ'))
    )
);

CREATE TABLE IF NOT EXISTS holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trader_id VARCHAR(32) NOT NULL,
    stock VARCHAR(32) NOT NULL CHECK (stock = UPPER(stock)),
    sector VARCHAR(64) NOT NULL CHECK (sector IN ('TECH', 'FINANCE', 'ENERGY', 'HEALTHCARE')),
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    CONSTRAINT fk_holdings_trader FOREIGN KEY (trader_id) REFERENCES traders(id),
    CONSTRAINT uk_holdings_trader_stock UNIQUE (trader_id, stock),
    CONSTRAINT ck_holdings_stock_sector CHECK (
        (sector = 'TECH' AND stock IN ('AAPL', 'MSFT', 'GOOGL', 'TSLA', 'NVDA'))
        OR (sector = 'FINANCE' AND stock IN ('JPM', 'GS', 'BAC', 'MS', 'WFC'))
        OR (sector = 'ENERGY' AND stock IN ('XOM'))
        OR (sector = 'HEALTHCARE' AND stock IN ('JNJ'))
    )
);
